services:
  # A Docker web service
  - type: web
    name: flow
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/hanzoai/flow
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: FLOW_DATABASE_URL
        value: sqlite:////app/data/.cache/flow/flow.db
      - key: FLOW_HOST
        value: 0.0.0.0
      - key: FLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: FLOW_LOG_LEVEL
        value: INFO
    disk:
      name: flow-data
      mountPath: /app/data
