services:
  # A Docker web service
  - type: web
    name: hanzoflow
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/hanzoflow-ai/hanzoflow
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: HANZOFLOW_DATABASE_URL
        value: sqlite:////app/data/.cache/hanzoflow/hanzoflow.db
      - key: HANZOFLOW_HOST
        value: 0.0.0.0
      - key: HANZOFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: HANZOFLOW_LOG_LEVEL
        value: INFO
    disk:
      name: hanzoflow-data
      mountPath: /app/data
