services:
  hanzoflow:
    image: hanzoflowai/hanzoflow:latest # or another version tag on https://hub.docker.com/r/hanzoflowai/hanzoflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - HANZOFLOW_DATABASE_URL=postgresql://hanzoflow:hanzoflow@postgres:5432/hanzoflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - HANZOFLOW_CONFIG_DIR=app/hanzoflow
    volumes:
      - hanzoflow-data:/app/hanzoflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: hanzoflow
      POSTGRES_PASSWORD: hanzoflow
      POSTGRES_DB: hanzoflow
    ports:
      - "5432:5432"
    volumes:
      - hanzoflow-postgres:/var/lib/postgresql/data

volumes:
  hanzoflow-postgres:
  hanzoflow-data:
