networks:
  dev-flow:

services:
  flow:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-flow
    container_name: dev-flow
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - FLOW_DATABASE_URL=postgresql://flow:flow@postgres:5432/flow
      - FLOW_SUPERUSER=flow
      - FLOW_SUPERUSER_PASSWORD=flow
      - FLOW_CONFIG_DIR=/var/lib/flow
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-flow


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: flow
      POSTGRES_PASSWORD: flow
      POSTGRES_DB: flow
    ports:
      - "5432:5432"
    networks:
      -  dev-flow

