networks:
  dev-hanzoflow:

services:
  hanzoflow:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-hanzoflow
    container_name: dev-hanzoflow
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - HANZOFLOW_DATABASE_URL=postgresql://hanzoflow:hanzoflow@postgres:5432/hanzoflow
      - HANZOFLOW_SUPERUSER=hanzoflow
      - HANZOFLOW_SUPERUSER_PASSWORD=hanzoflow
      - HANZOFLOW_CONFIG_DIR=/var/lib/hanzoflow
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-hanzoflow


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: hanzoflow
      POSTGRES_PASSWORD: hanzoflow
      POSTGRES_DB: hanzoflow
    ports:
      - "5432:5432"
    networks:
      -  dev-hanzoflow

